### PR TITLE
Created Avatar component

### PR DESCRIPTION
**Pull request by sagargse**
Created Avatar component

### CODE REVIEW

**Review by Rockyraven — APPROVED** [review]
all goods for me

**Comment by AtulHande03a** [comment]
try to stick to one convention while naming css classes like badge-container  and not badge-md-container. Rest all looks fine

**Comment by sagargse** [comment]
> try to stick to one convention while naming css classes like badge-container and not badge-md-container. Rest all looks fine

ok i will resolve that

**Comment by sagargse** [comment]
> all goods for me

okay!

**Pull request merged**
